<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:39:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "a9fe0ec22a54235e6acbc5d32aec3200",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:38:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "bed7413d8529ffa449d4cd8754d1e25a",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:37:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "29599e1f94855d6d654809469bf39ebc",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2026-05-17 18:36:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "80d5ada720c5b1eed2712ec31066d6ec",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "home": {
        "title": "Home",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:00:00",
        "dateModified": "",
        "allowComments": false,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "11111111111111111111111111111111",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "states": {
        "title": "States",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:01:00",
        "dateModified": "",
        "allowComments": false,
        "position": 2,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "22222222222222222222222222222222",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "challenges": {
        "title": "Challenges",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:02:00",
        "dateModified": "",
        "allowComments": false,
        "position": 3,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "33333333333333333333333333333333",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "more": {
        "title": "More",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:03:00",
        "dateModified": "",
        "allowComments": false,
        "position": 4,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "44444444444444444444444444444444",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "contact": {
        "title": "Contact",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:04:00",
        "dateModified": "",
        "allowComments": false,
        "position": 5,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "55555555555555555555555555555555",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "kansas": {
        "title": "Kansas",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:05:00",
        "dateModified": "",
        "allowComments": false,
        "position": 6,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "66666666666666666666666666666666",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "colorado": {
        "title": "Colorado",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:06:00",
        "dateModified": "",
        "allowComments": false,
        "position": 7,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "77777777777777777777777777777777",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}