<?php defined('BLUDIT') or die('Bludit CMS.'); ?>
{
    "create-your-own-content": {
        "title": "Create your own content",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:39:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "a9fe0ec22a54235e6acbc5d32aec3200",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "set-up-your-new-site": {
        "title": "Set up your new site",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:38:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "bed7413d8529ffa449d4cd8754d1e25a",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "follow-bludit": {
        "title": "Follow Bludit",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 18:37:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "29599e1f94855d6d654809469bf39ebc",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "about": {
        "title": "About",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "static",
        "date": "2026-05-17 18:36:39",
        "dateModified": "",
        "allowComments": true,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "80d5ada720c5b1eed2712ec31066d6ec",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "home": {
        "title": "Home",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:00:00",
        "dateModified": "",
        "allowComments": false,
        "position": 1,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "11111111111111111111111111111111",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "states": {
        "title": "States",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:01:00",
        "dateModified": "",
        "allowComments": false,
        "position": 2,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "22222222222222222222222222222222",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "challenges": {
        "title": "Challenges",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:02:00",
        "dateModified": "",
        "allowComments": false,
        "position": 3,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "33333333333333333333333333333333",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "more": {
        "title": "More",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:03:00",
        "dateModified": "",
        "allowComments": false,
        "position": 4,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "44444444444444444444444444444444",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "contact": {
        "title": "Contact",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:04:00",
        "dateModified": "",
        "allowComments": false,
        "position": 5,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "55555555555555555555555555555555",
        "parent": "",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "kansas": {
        "title": "Kansas",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:05:00",
        "dateModified": "",
        "allowComments": false,
        "position": 71,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "66666666666666666666666666666666",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "colorado": {
        "title": "Colorado",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-17 19:06:00",
        "dateModified": "",
        "allowComments": false,
        "position": 64,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "77777777777777777777777777777777",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "al": {
        "title": "Alabama",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:00:00",
        "dateModified": "",
        "allowComments": false,
        "position": 60,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "029d2e4c57026367267e2235ea7508a7",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "az": {
        "title": "Arizona",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:01:00",
        "dateModified": "",
        "allowComments": false,
        "position": 61,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "46a014f8dfee939083a6cf7cfd268f52",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ar": {
        "title": "Arkansas",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:02:00",
        "dateModified": "",
        "allowComments": false,
        "position": 62,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "0a34683f59e5237a008e7be67919c0d7",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ca": {
        "title": "California",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:03:00",
        "dateModified": "",
        "allowComments": false,
        "position": 63,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "cdb44bad4eeb765c94953e7c5065caa5",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "fl": {
        "title": "Florida",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:05:00",
        "dateModified": "",
        "allowComments": false,
        "position": 65,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "00096b6817b7cc132e19ee02ecde5855",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ga": {
        "title": "Georgia",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:06:00",
        "dateModified": "",
        "allowComments": false,
        "position": 66,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "9e0ca8136a6052ee499c6534364422d0",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "id": {
        "title": "Idaho",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:07:00",
        "dateModified": "",
        "allowComments": false,
        "position": 67,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "450674e98e8634169704b938845b8561",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "il": {
        "title": "Illinois",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:08:00",
        "dateModified": "",
        "allowComments": false,
        "position": 68,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "315d388109d3f873ed421afc79b3d9ee",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "in": {
        "title": "Indiana",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:09:00",
        "dateModified": "",
        "allowComments": false,
        "position": 69,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "f9fd8c07aaaa0e9b122e90d95df3bfc5",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ia": {
        "title": "Iowa",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:10:00",
        "dateModified": "",
        "allowComments": false,
        "position": 70,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "fb140cf7d789fdd9fb1f0bb6f40223c4",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ky": {
        "title": "Kentucky",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:12:00",
        "dateModified": "",
        "allowComments": false,
        "position": 72,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "b264d2fddef5358245a7591180cb24b7",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "la": {
        "title": "Louisiana",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:13:00",
        "dateModified": "",
        "allowComments": false,
        "position": 73,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "834dd872d690c4c27e6b65e3f978bbf3",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "md": {
        "title": "Maryland",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:14:00",
        "dateModified": "",
        "allowComments": false,
        "position": 74,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "0f022745ae28343b339a3d971562fdcb",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "mi": {
        "title": "Michigan",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:15:00",
        "dateModified": "",
        "allowComments": false,
        "position": 75,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "95985ad7d61d96c28bb9e58db8978486",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "mn": {
        "title": "Minnesota",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:16:00",
        "dateModified": "",
        "allowComments": false,
        "position": 76,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "4491f5eb16414cc0a800be46b424b23c",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ms": {
        "title": "Mississippi",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:17:00",
        "dateModified": "",
        "allowComments": false,
        "position": 77,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "28db55487097b5c0604ccab61080e91c",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "mo": {
        "title": "Missouri",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:18:00",
        "dateModified": "",
        "allowComments": false,
        "position": 78,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "6698e0cf945f862be5a90f279dc78186",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "mt": {
        "title": "Montana",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:19:00",
        "dateModified": "",
        "allowComments": false,
        "position": 79,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "78f3eb488c2ee70a3da2aac2b908c820",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ne": {
        "title": "Nebraska",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:20:00",
        "dateModified": "",
        "allowComments": false,
        "position": 80,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "2b73b7557686c1720cc9d03966f5dae3",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "nd": {
        "title": "North Dakota",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:21:00",
        "dateModified": "",
        "allowComments": false,
        "position": 81,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "d88970794bed5b8b49386523858b6a99",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "nm": {
        "title": "New Mexico",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:22:00",
        "dateModified": "",
        "allowComments": false,
        "position": 82,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "e108f7d5f6800c2fc02024fa2c29bba3",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "nv": {
        "title": "Nevada",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:23:00",
        "dateModified": "",
        "allowComments": false,
        "position": 83,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "65b13d6b9a0591f0e70ca0b1177987af",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "oh": {
        "title": "Ohio",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:24:00",
        "dateModified": "",
        "allowComments": false,
        "position": 84,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "776e7fbc869a43f02766c8b38cbbe869",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ok": {
        "title": "Oklahoma",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:25:00",
        "dateModified": "",
        "allowComments": false,
        "position": 85,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "71d11783b3b9b6e9014a04ffb5b65aec",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "pa": {
        "title": "Pennsylvania",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:26:00",
        "dateModified": "",
        "allowComments": false,
        "position": 86,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "a93a142fc17b44b1cae1bfc1c472deb4",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "sd": {
        "title": "South Dakota",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:27:00",
        "dateModified": "",
        "allowComments": false,
        "position": 87,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "2ce4c5f69407ffe715e059659ad06630",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "tn": {
        "title": "Tennessee",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:28:00",
        "dateModified": "",
        "allowComments": false,
        "position": 88,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "86f4198171a8d0567e2210e036e58c96",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "tx": {
        "title": "Texas",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:29:00",
        "dateModified": "",
        "allowComments": false,
        "position": 89,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "9f5ffc0520c851d9ddaecf18df0ffd9a",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "ut": {
        "title": "Utah",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:30:00",
        "dateModified": "",
        "allowComments": false,
        "position": 90,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "172af0c6731029915040768e9b1d24db",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "va": {
        "title": "Virginia",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:31:00",
        "dateModified": "",
        "allowComments": false,
        "position": 91,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "aecdac6508c4369aa0a96543b4a98099",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "wi": {
        "title": "Wisconsin",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:32:00",
        "dateModified": "",
        "allowComments": false,
        "position": 92,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "cd371d5a1786143f10a81e3091f3e665",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "wv": {
        "title": "West Virginia",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:33:00",
        "dateModified": "",
        "allowComments": false,
        "position": 93,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "ee80f8f64dc615bb32fe53b348bf40f2",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    },
    "wy": {
        "title": "Wyoming",
        "description": "",
        "username": "admin",
        "tags": [],
        "type": "published",
        "date": "2026-05-18 12:34:00",
        "dateModified": "",
        "allowComments": false,
        "position": 94,
        "coverImage": "",
        "md5file": "",
        "category": "general",
        "uuid": "b850866cb30bed166fb320e8fc541fa0",
        "parent": "states",
        "template": "",
        "noindex": false,
        "nofollow": false,
        "noarchive": false
    }
}
